version: '3'

services:
  # Application
  database:
    container_name: nest-prazer-oculto-database
    image: 'bitnami/postgresql'
    ports:
      - '5445:5432'
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}  
    volumes:
      - 'postgresql_data:/bitnami/postgresql'

volumes:
  postgresql_data:
    driver: local
